horntail0/SSDProject

SSDProject/Shell/shell.cpp
SSDProject/Shell_TC/test.cpp

Test : Help 함수 & 테스트 코드 추가하였습니다.

Test : Help 함수 & 테스트 코드 추가

---

SSDProject/SSD/File.cpp
SSDProject/SSD/SSD.cpp
SSDProject/SSD_TC/test.cpp

Test: add test for ssd read

---

SSDProject/Shell/shell.cpp
SSDProject/Shell_TC/test.cpp

Test : Full Read 함수 & 테스트 코드 추가하였습니다.

Test : Full Read 함수 & 테스트 코드 추가

---

SSDProject/SSD_TC/test.cpp
SSDProject/Shell/shell.cpp
SSDProject/Shell_TC/test.cpp

Test : Full Write 코드 기능 구현 & 테스트 완료하였습니다.

Test : Full Write 코드 기능 구현 & 테스트 완료

---

SSDProject/Shell/main.cpp
SSDProject/Shell/shell.cpp

Feat : main 루프 코드 작성

---

SSDProject/Shell/shell.cpp
SSDProject/Shell_TC/test.cpp

Test : TestApp1 스크립트 코드 작성

---

SSDProject/SSD/File.cpp
SSDProject/SSD/SSD.cpp
SSDProject/SSD_TC/test.cpp

rand를 읽고, result에 쓰기 위한 용도로 private method를 만들었습니다.

feat: add writeFile Test

---

SSDProject/Shell/shell.cpp
SSDProject/Shell_TC/test.cpp

Shell Test App2 스크립트 코드를 작성하였습니다.

Test : Test App2 스크립트 코드 작성

---

SSDProject/Shell/shell.cpp
SSDProject/Shell_TC/test.cpp

Test App1 코드가 true/false를 반환하도록 코드를 수정하였습니다.

Test : Test App1 코드 수정

---

SSDProject/SSD/File.cpp
SSDProject/SSD_TC/test.cpp

file write 기능 구현입니다. 리뷰 부탁드립니다.

[feat] implement file write function

---

SSDProject/SSD/main.cpp

SSD command(W, R) 처리를 위한 initial code 구현입니다.

[feat] implement SSD argument handling

---

SSDProject/SSD/main.cpp

feat: add read command

---

SSDProject/Shell/SSDAdapter.cpp
SSDProject/Shell/SSDInterface.cpp
SSDProject/Shell/Shell.vcxproj
SSDProject/Shell/Shell.vcxproj.filters
SSDProject/Shell/shell.cpp
SSDProject/Shell_TC/test.cpp

SSDAdapter, MockSSDAdapter, MockFile 클래스 작성 및 Read 테스트 완료하였습니다

Feat : SSDAdapter, MockSSDAdapter, MockFile 클래스 작성 및 Read 테스트 완료

---

SSDProject/SSD/File.cpp

Refactor: modify writeFileTotal

---

SSDProject/SSD/main.cpp

argument 갯수가 맞지 않을 경우 바로 return 하는 코드입니다

[feat] ssd.exe invalid argc handling

---

SSDProject/.editorconfig
SSDProject/SSD/File.cpp
SSDProject/SSD/SSD.cpp
SSDProject/SSD_TC/test.cpp
SSDProject/Shell/SSDInterface.cpp
SSDProject/Shell/shell.cpp
SSDProject/Shell_TC/test.cpp

coding standard 용 editorconfig 및 현재 맞춰줘있지 않는 부분 formatting 하였습니다.
( 중괄호 개행 및 줄 마지막 공백글자 제거 )

Style: Coding Standard 맞지 않은 코드들 수정 및 Editorconfig 추가

---

SSDProject/.gitignore
SSDProject/Shell/SSDAdapter.cpp

Feat : SSDAdapter 클래스 작성

---

SSDProject/SSD/File.cpp

file name을 const string으로 처리했습니다.

[refactor] nand.txt filename to macro

---

SSDProject/SSD_TC/test.cpp

test에서 직접 file을 읽어서 결과값을 비교할 수 있도록 했습니다.

[test] add test for ssd write command

---

SSDProject/Shell_TC/test.cpp

Test : Shell Help, Exit 코드를 작성하였습니다

Test : Shell Help, Exit 코드 작성

---

SSDProject/Shell_TC/test.cpp

Test : FullRead, FullWrite 테스트 코드를 작성하였습니다

Test : FullRead, FullWrite 테스트 코드 작성

---

SSDProject/Shell_TC/test.cpp

Test : TestApp1 테스트 코드를 작성하였습니다

Test : TestApp1 테스트 코드 작성

---

SSDProject/Shell_TC/test.cpp

Test : TestApp2 테스트 코드를 작성하였습니다

Test : TestApp2 테스트 코드 작성

---

SSDProject/Shell_TC/test.cpp

Fix : TestApp1에 누락된 코드를 수정하였습니다

Fix : TestApp1 에러 코드 수정

---

SSDProject/Shell/main.cpp

Feat : TestApp1, TestApp2 코드를 작성하였습니다

Feat : TestApp1, TestApp2 코드 작성

---

SSDProject/Shell_TC/test.cpp

Test: Write 코드 작성

---

SSDProject/SSD/File.cpp
SSDProject/SSD_TC/test.cpp

[Test] add test for ssd read

---

SSDProject/SSD/SSD.cpp

작은 function으로 refactoring을 진행했습니다.

refactoring: SSD write의 invalid argument check를 작은 function으로 분리했습니다

---

SSDProject/SSD_TC/test.cpp

Update SSD write TC
2번 이상 normal write
nand.txt 파일 전체 비교

test: update TC for SSD writing with invalid argument

---

SSDProject/.gitignore
SSDProject/Shell/shell.cpp
SSDProject/Shell_TC/test.cpp

Test : 코드 커버리지 확보용 추가 TC

---

SSDProject/SSD/File.cpp
SSDProject/SSD_TC/test.cpp

read test 추가 및 관련 코드 수정하여 test coverage를 높였습니다.

[Feat] modify read test

---

SSDProject/SSD/File.cpp

[refactor] modify write method

---

SSDProject/SSD/File.cpp
SSDProject/SSD/SSD.cpp
SSDProject/SSD_TC/test.cpp

erase method 추가했습니다. 간단한 테스트도 추가했습니다.

[feat] add erase method

---

SSDProject/SSD/main.cpp

feat: add E command in main

---

SSDProject/Shell/Runner.cpp
SSDProject/Shell/Runner.h
SSDProject/Shell/Shell.vcxproj
SSDProject/Shell/Shell.vcxproj.filters
SSDProject/Shell/main.cpp
SSDProject/x64/Debug/run_list.lst

Feat : Runner 클래스 생성 및 기초 동작 테스트하였습니다.
아직 testapp1, testapp2가 동작하지는 않고 라인by라인 인식까지만 완료한 상태입니다.

Feat : Runner 클래스 생성 및 기초 동작 테스트

---

SSDProject/SSD/SSD.cpp
SSDProject/SSD/main.cpp

F, WB, EB command 추가
method 추가

feat: add method for buffered operation and flush

---

SSDProject/Shell/Runner.cpp
SSDProject/Shell/SSDAdapter.cpp
SSDProject/Shell/SSDAdapter.h
SSDProject/Shell/SSDInterface.h
SSDProject/Shell/main.cpp
SSDProject/Shell/shell.cpp
SSDProject/Shell/shell.h
SSDProject/Shell_TC/test.cpp

Runner 클래스에서 print 출력을 제어할 수 있도록 변수 추가 및 테스트 완료하였습니다

Feat : Runner 클래스에서 print 출력을 제어할 수 있도록 변수 추가 및 테스트 완료

---

SSDProject/Shell/Runner.cpp
SSDProject/Shell/shell.cpp
SSDProject/Shell/shell.h
SSDProject/x64/Debug/run_list.lst

Wrtie10AndCompare, LoopWriteAndCompare 코드 추가 및 테스트 완료하였습니다

Feat : Wrtie10AndCompare, LoopWriteAndCompare 코드 추가 및 테스트 완료

---

SSDProject/Shell_TC/test.cpp

Fix : Test가 Fail되지 않도록 TestApp1의 파라미터를 변경하는 코드 추가하였습니다

Fix : Test가 Fail되지 않도록 TestApp1의 파라미터를 변경하는 코드 추가

---

SSDProject/SSD/File.cpp
SSDProject/SSD/SSD.cpp
SSDProject/SSD_TC/test.cpp

[feat] implement buffer write with flush

---

SSDProject/SSD/SSD.cpp
SSDProject/SSD_TC/test.cpp
SSDProject/Shell_TC/test.cpp

fastWrite 구현 및 간단한 테스트 완료하였습니다.
fastRead는 뼈대만 구성했습니다.

[Feat] add fastbuffer

---

SSDProject/Shell/Runner.cpp
SSDProject/Shell/Runner.h
SSDProject/Shell/main.cpp

Refactor : Runner 클래스를 리팩토링하였습니다
생성자에서 바로 filePath를 받도록 수정하였으며 printout --> printOut 카멜 표기법으로 변경하였습니다.

Refactor : Runner 클래스 리팩토링

---

SSDProject/Shell/Runner.cpp
SSDProject/Shell/Runner.h
SSDProject/Shell/SSDAdapter.cpp
SSDProject/Shell/SSDAdapter.h
SSDProject/Shell/SSDInterface.h
SSDProject/Shell/main.cpp
SSDProject/Shell/shell.cpp
SSDProject/Shell/shell.h
SSDProject/Shell_TC/test.cpp

Refactor: Singleton 패턴을 추가하였습니다

Refactor: Singleton 패턴 추가

---

SSDProject/Shell/Runner.cpp

Fix : Merge Resolve 도중 잘못 병합한 부분 수정

Fix : Merge Resolve 도중 잘못 병합한 부분 수정

---

SSDProject/SSD_TC/test.cpp

[feat] add TC for buffer write, erase

---

SSDProject/SSD/File.cpp
SSDProject/SSD/SSD.cpp
SSDProject/SSD_TC/test.cpp
SSDProject/Shell_TC/test.cpp

fast read 할 때의 file read 하는 부분을 수정했습니다. 
api가 아닌 부분들은 private으로 옮겼습니다.

[refactor] refactor read file

---

SSDProject/SSD/SSD.cpp

중복 코드를  fast write에 넣었습니다.
중복된 command를 지우는 부분을 따로 메서드로 빼냈습니다.

[refactor] refactor fast write

---

SSDProject/SSD/File.cpp
SSDProject/SSD/SSD.cpp

TC의 file check 및 변수 이름, macro 등에 대한 refactoring을 진행했습니다.

[refactoring] SSD TC 및 buffer 관련 refactoring

---

SSDProject/SSD/SSD.cpp

fix: fix compile error for cmdBuf naming

---

SSDProject/SSD/File.cpp
SSDProject/SSD/SSD.cpp

[refactor] refactor file

---

SSDProject/Shell/shell.cpp
SSDProject/Shell/shell.h

Refactor : 카멜 표기법에 따라 SsdDriver --> ssdDriver 변경하였습니다

Refactor : 카멜 표기법에 따라 SsdDriver --> ssdDriver 변경

---

SSDProject/SSD/SSD.cpp

[refactoring] extract lba check to function

---

SSDProject/Shell/LoopWriteAndReadCompare.cpp
SSDProject/Shell/LoopWriteAndReadCompare.h
SSDProject/Shell/Runner.cpp
SSDProject/Shell/Runner.h
SSDProject/Shell/ShellTestBuilder.cpp
SSDProject/Shell/ShellTestBuilder.h
SSDProject/Shell/TestCase.h
SSDProject/Shell/main.cpp
SSDProject/Shell/shell.cpp
SSDProject/Shell/shell.h
SSDProject/Shell/testapp1.cpp
SSDProject/Shell/testapp1.h
SSDProject/Shell/testapp2.cpp
SSDProject/Shell/testapp2.h
SSDProject/Shell/write10andcompare.cpp
SSDProject/Shell/write10andcompare.h

Feat : 사용 가능한 테스트 시나리오 목록을 출력하는 기능 추가하였습니다.
쉘에서 잘못된 커맨드 (e.g., testappp1, apptest1 등)을 입력하였을 경우 
Available Test Scenario:
testapp1
testapp2
write10andcompare
loopwriteandreadcompare
와 같이 테스트 시나리오의 목록이 출력됩니다.

Feat : 사용 가능한 테스트 시나리오 목록을 출력하는 기능 추가

---

SSDProject/Shell/ShellTestBuilder.h

test case max 개수 를 define 하였습니다.

Refact: add MAX_TESTCASE_NUM define

---

SSDProject/SSD/SSD.cpp

flush count from magic number to macro.
remove compile warning

[refactoring] ssd flush count macro

---

SSDProject/SSD/main.cpp

enable buffered write, erase with W, E command

[feat] enable buffered write, erase

---

SSDProject/SSD/main.cpp

[fix] handle 2 argument in main

---

SSDProject/Shell/main.cpp

Feat : main문에 argc, argv를 입력으로 받아서 shell.exe {command} 명령이 가능하도록 수정하였습니다

Feat : main문에 argc, argv를 입력으로 받아서 shell.exe {command} 명령이 가능하도록 수정

---

SSDProject/Shell/SSDAdapter.cpp
SSDProject/Shell/SSDAdapter.h
SSDProject/Shell/SSDInterface.h
SSDProject/Shell/main.cpp
SSDProject/Shell/shell.cpp
SSDProject/Shell/shell.h
SSDProject/Shell_TC/test.cpp

Feat : flush 기능을 추가하였습니다. 
내부적으로 'SSD.exe F' 커맨드를 호출합니다.

Feat : flush 기능 추가

---

SSDProject/Shell/main.cpp

Refactor : showHelp() 함수 추가하여 코드 중복 방지하였습니다.

Refactor : showHelp() 함수 추가하여 코드 중복 방지

---

SSDProject/Shell/main.cpp
SSDProject/Shell/shell.cpp

stoi() 함수에 숫자로 변환할 수 없는 string이 입력되는 invalid_argument exception이 발생하고 있습니다. 이부분에 대한 예외처리를 try/catch문으로 방어했습니다.

[Feat] 입력 LBA로 숫자가 아닌 string이 들어올 경우 예외 처리

---

SSDProject/Shell/main.cpp

shell.exe에서 fullwrite가 실행 안 되는 에러 수정하였습니다.
그리고 erase, erase_range 범위 예외처리 수정하였습니다.

Fix : fullwrite, erase, erase_range 버그 수정

---

SSDProject/Shell/main.cpp

Fix : erase, erase_range 범위 수정하였습니다. 
음수가 나오거나 param2가 param1보다 큰 경우 예외처리하였습니다.

Fix : erase, erase_range 범위 수정
